### ISSUE TITLE
Why is only ISOLATION_LEVEL_READ_COMMITTED supported?

### ISSUE THREAD

**Issue by TimNN** [aio-libs/aiopg#105]
As the title states, I'm curious to know why the documentation states that only `ISOLATION_LEVEL_READ_COMMITTED` is supported.

**Edit:** I've just been looking at the `psycopg2` documentation. Would I be correct to assume that other isolation levels are actually supported, but **setting** them using the `set_isolation_level` api is unsupported?

**Comment by asvetlov** [comment]
Yes, you may change isolation level by sql calls but `set_isolation_level` is actually forbidden in async mode.

**Comment by TimNN** [comment]
Thanks for the answer! In hindsight that actually makes sense because `set_isolation_level` is a synchronous method in `psychopg2` which would of course never work in an asynchronous environment.
