### ISSUE TITLE
Exception in Connection.__del__ when database connection has failed.

### ISSUE THREAD

**Issue by elektito** [aio-libs/aiopg#110]
Try the following code snippet:

    import asyncio
	import aiopg
	import psycopg2

	async def run():
	    try:
		pool = await aiopg.create_pool('dbname=foo host=bar')
	    except psycopg2.OperationalError:
		pass

	def main():
	    loop = asyncio.get_event_loop()
	    loop.run_until_complete(run())

	if __name__ == '__main__':
	    main()

If `foo` is a database that **does** exist and `bar` a host that **does not**, you'll receive the following error:

	Exception ignored in: <bound method Connection.__del__ of <aiopg.connection.Connection object at 0x7ffff4d90358>>
	Traceback (most recent call last):
	  File "/home/mostafa/source/salesman/venv/lib/python3.5/site-packages/aiopg/connection.py", line 452, in __del__
	      if not self._conn.closed:
	AttributeError: 'Connection' object has no attribute '_conn'

We should probably either check if `_conn` exists, or make sure it does exist even if the `connect` method fails.

**Comment by mpaolini** [comment]
fixed in #124
