### ISSUE TITLE
Setting up application name

### ISSUE THREAD

**Issue by extremely-cool** [aio-libs/aiopg#120]
It would be great if for the connection pool could be install the application name
e.g. SQL "SET application_name = %s'' operation.
it's very convenient when you have many connections from multiple applications.

**Comment by bitdancer** [comment]
You can put application_name in the dsn string you pass to create_pool.  Is anything more needed?

**Comment by extremely-cool** [comment]
Oh, thanks a lot, David!
I lost sight of this https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
