### ISSUE TITLE
Acquiring connections in a nested manner

### ISSUE THREAD

**Issue by serg666** [aio-libs/aiopg#127]
Guys, sorry for annoying, but all your answers in #113 #125 #126 are not at problem described at issues.

The point of #113 is that we can deadlock the pool if we acquire two connections in a nested manner in case if concurrency is more then pool size . In #113 #125 #126 you propose to use a timeout, or does not use a nested style at all as @asvetlov  commented at  the #113

The question is "**_can we acquire connections in a nested manner_**" as described in #113 at the first example

**Comment by mpaolini** [comment]
I don't think it makes any sense acquiring connections in nested manner

**Comment by serg666** [comment]
No no no! It MAKES SENSE! Can you see my example at #113 and #126?

**Comment by serg666** [comment]
You can even see your own example in # 113

**Comment by serg666** [comment]
Ad @asvetlov  said at #126 "It is an architectural error, nothing more."

**Comment by mpaolini** [comment]
My example in #113, I just wrote it for triggering the deadlock you mentioned, but I am quite sure as @asvetlov says that trying to acquire nested connections is a programming error, or at least not supported by aiopg. @asvetlov what's your take on this?

This is the updated script that shows the use of timeout for avoiding deadlocks in that case. Please note that deadlock s not completely avoided because you can have 10 "root level" `.acquire()` that all run before the nested ones. In this case the deadlock is unavoidable even  using timeouts.

```python
import asyncio
import logging
import traceback

import aiopg.sa

logger = logging.getLogger()

CONN_STRING = 'postgresql://test:test@127.0.0.1/aiopg_test'


class acquire_retry:

    retry_sleep = 1

    def __init__(self, engine, timeout, loop, task_id):
        self._engine = engine
        self._timeout = timeout
        self._loop = loop
        self._task_id = task_id

    async def __aenter__(self):
        while True:
            try:
                self._conn = await asyncio.wait_for(
                    self._engine.acquire(),
                    loop=self._loop,
                    timeout=self._timeout
                )
            except asyncio.TimeoutError:
                logger.warning('timeout on acquiring connection for task {}'.format(self._task_id))
                await asyncio.sleep(self.retry_sleep)
            else:
                return self._conn

    async def __aexit__(self, ext_type, exc_value, traceback):
        await self._conn.close()


async def q2(engine, task_id, timeout, loop):
    logger.debug('starting task {}'.format(task_id))
    async with acquire_retry(engine, timeout, loop, task_id):
        logger.debug('acquired conn task {}'.format(task_id))
    logger.debug('released conn task {}'.format(task_id))


async def q1(engine, task_id, nested, timeout, loop):
    logger.debug('starting task {}'.format(task_id))
    async with acquire_retry(engine, timeout, loop, task_id):
        logger.debug('acquired conn task {}'.format(task_id))
        if nested:
            await q2(engine, task_id, timeout, loop)


async def main(concurrency, iterations, pool_size, nested, timeout, loop):
    async with aiopg.sa.create_engine(CONN_STRING, maxsize=pool_size) as engine:
        for n in range(iterations):
            print('iteration={n}'.format_map(locals()))
            tasks = [q1(engine, i, nested, timeout, loop) for i in range(concurrency)]
            done, _ = await asyncio.wait(tasks, loop=loop)
            for fut in done:
                if fut.exception():
                    print(fut.exception())
                    print(traceback.print_tb(fut.exception().__traceback__))


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--concurrency', type=int, default=10)
    parser.add_argument('-i', '--iterations', type=int, default=10)
    parser.add_argument('-p', '--pool-size', type=int, default=10)
    parser.add_argument('-n', '--nested', action='store_true')
    parser.add_argument('-t', '--timeout', type=int)
    args = parser.parse_args()
    loop = asyncio.get_event_loop()
    logging.basicConfig(level=logging.DEBUG, format='%(funcName)s %(lineno)d: %(message)s')
    loop.run_until_complete(main(args.concurrency, args.iterations, args.pool_size, args.nested,
                                 args.timeout, loop=loop))
```

**Comment by serg666** [comment]
Yes, the question is "is it a programming error, or at least not supported by aiopg"? At least acquiring connections in a nested manner works until concurrency < pool size

**Comment by mpaolini** [comment]
for instance pymongo has this `waitQueueMultiple` [to cap the number of waiting threads in a connection pool](https://api.mongodb.com/python/current/faq.html?highlight=pool#how-does-connection-pooling-work-in-pymongo) . When that number is reached, an exception in raised when trying to acquire a new connection from the pool. Note that they also have the `timeout` option on the connection pool waiting feature

**Comment by serg666** [comment]
I can try to explain, why I need to acquire connections in a nested manner. For example, I have got some handler to serve incoming POST request

```
class ReqHandler(tornado.web.RequestHandler):
    async def post(self):
        async with engine.acquire() as conn:
            ...
```

and inside post I acquire new connection to serve this request. For example, I want to validate and convert incoming request with FormEncode and I want to use something like this

```
class ReqHandler(tornado.web.RequestHandler):
    async def post(self):
        async with engine.acquire() as conn:
            transaction_id = self.BODY.get('transaction')
            transaction = await transaction_id.transaction
            ...
```

so in FromEncode validator I have something like this

```
from formencode.schema import Schema
from formencode.api import FancyValidator
....
from something import model as m


class TransactionID(FancyValidator):
    class converter(int):
        @property
        async def transaction(self):
            async with engine.acquire() as conn:
                res = await conn.execute(m.transactions.select().
                                         where(m.transactions.c.id == self))
                trans = await res.fetchone()
                if trans is None:
                    raise exceptions.InvalidTransaction(self)
                return trans

    def _to_python(self, value, state):
        try:
            transaction_id = self.converter(value)
        except ValueError:
            raise exceptions.InvalidTransaction(value)
        return transaction_id


class SomeSchema(Schema):
    transaction = TransactionID(not_empty=True)

```

So I want to use property 

`transaction = await transaction_id.transaction`

where I can not pass already acquired connection.

**Comment by mpaolini** [comment]
In this case opening two psql connections in the same coroutine is suboptimal IMHO, why don't you store the current connection in a task-local variable?

see https://github.com/azazel75/metapensiero.asyncio.tasklocal

```python

CONNECTIONS = {}

def get_connection(looop):
    global CONNECTIONS
    return CONNECTIONS[asyncio.Task.current_task(loop)]
```

**Comment by serg666** [comment]
U are right. two psql connections in the same coroutine is suboptimal. I ask theoretically why we can not acquiring to connections in a nested manner)

**Comment by mpaolini** [comment]
well, nested connection acquire in a pool could only make sense if the pool was reentrant (asyncio-task-wise). That is, the pool understands that the *same asyncio task* is acquiring a new connection and thus returns the same connection that was acquired previously by the same task. This would indeed make your use case easier to implement. @asvetlov What do you think?

**Comment by serg666** [comment]
It would be great, Or I can implement with my own with

```
CONNECTIONS = {}

def get_connection(looop):
    global CONNECTIONS
    return CONNECTIONS[asyncio.Task.current_task(loop)]
```
