### ISSUE TITLE
Using cursors with SQLAlchemy 

### ISSUE THREAD

**Issue by tomas-fp** [aio-libs/aiopg#140]
First of all, thank you for the great job publishing this package.

I would like to know how to properly use a cursor using SQLAlchemy abstraction in `aiopg`.
Looks like the `sa` subpackage is using internally a cursor.

Would you mind sharing an example about how to use it?

**Comment by asvetlov** [comment]
Are you asking for https://github.com/aio-libs/aiopg/blob/master/examples/simple_sa.py ?

**Comment by tomas-fp** [comment]
I was just digging into the code and [ResultProxy](https://aiopg.readthedocs.io/en/stable/sa.html#resultproxy) returned by `connection()` provides all I need, I believe, since it encapsulates a current connection cursor.

I simply want to use a server-side cursor to efficiently retrieve a very large data set. What's your recommendation for doing this? Thanks.

**Comment by asvetlov** [comment]
Sorry, server side cursors are not supported by psycopg2 in async mode.
aiopg is built on top of psycopg2. If core library doesn't support the feature -- aiopg doesn't support it too.

**Comment by tomas-fp** [comment]
What alternative approaches can I use to retrieve large data set as sort of streaming/scrolling strategy without buffering everything in memory? Thanks!

**Comment by asvetlov** [comment]
Honestly I don't know.
Maybe https://github.com/MagicStack/asyncpg library fits to your task better?

**Comment by tomas-fp** [comment]
I know about that driver, but looks like is not stable and versatile as aiopg. 
Will give it a try anyway, thank you!
