### ISSUE TITLE
Question: Is there two phase commit support?

### ISSUE THREAD

**Issue by toidi** [aio-libs/aiopg#179]
If yes - it would be good to have a quick example here.

Thank you.

**Comment by asvetlov** [comment]
Just execute the following commands line by line:
```
BEGIN;
update mytable set a_col='something' where red_id=1000;
PREPARE TRANSACTION 'foobar';
COMMIT PREPARED 'foobar';
```

**Comment by jettify** [comment]
`aiopg.sa` has explicit interface, take a look on tests:
https://github.com/aio-libs/aiopg/blob/master/tests/test_sa_transaction.py#L318-L343

**Comment by toidi** [comment]
Thanks. I found tests example especially useful.
