### ISSUE TITLE
mogrify doesn't need to be a coroutine

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aiopg#186]
Is there a good reason why [mogrify](https://github.com/aio-libs/aiopg/blob/fb5f28505debafd7b7f5961314dd6a9b28f3d616/aiopg/cursor.py#L149-L160) is a coroutine?

It's like to be used in "bulk create" operations where it'll be called a lot of times so it would have a margin improvement to performance to make it a simple function.

**Comment by asvetlov** [comment]
Even if it could be just a function it is a backward incompatible change.

What is "bulk create" and what performance boost do you expect?

**Comment by samuelcolvin** [comment]
bulk create was a reference to django's `bulk_create` method.

Eg. I guess one of the common uses of mogrify is in creating queries which insert multiple (likely thousands) of rows.

You do something like 
```python
ROW_SQL = b"(%(a)s,%(b)s,%(c)s,)"
async with conn.cursor() as cur:
    args = []
    for d in data:
        args.append(await cur.mogrify(ROW_SQL, d))
    await cur.execute(b'INSERT INTO entries (a, b, c) VALUES ' + b','.join(args))
```

Perhaps I'm missing something and there's an easier way to do this?

This works fine but:
* I thought there might be a slightly performance impact from the unnecessary `await`, I've tried a simple test now and there seems to be virtually no effect.
* you can't use `await` inside comprehensions which makes the above much less succinct than it should be. eg `args = [cur.mogrify(ROW_SQL, d) for d in data]` would be neater.
* I kind of assume it's bad practice to make methods `async` that don't need to be.

Surely it's better to fix things even if it causes an incompatible change, than leave it wrong; especially when the change is transparent and would fail in an easy to notice and fix way.

**Comment by asvetlov** [comment]
The only way to fix it is introducing `.mongrify2()` method.
Do you have performance measuring for proving significant speedup?

**Comment by asvetlov** [comment]
The only way to don't break backward compatibility is introducing `.mongrify2` method.

But it's not necessary because `psycopg2` does SQL escaping internally.

Moreover your example might be rewritten for producing really effective code by using implicit SQL query preparation:

```
ROW_SQL = b"(%(a)s,%(b)s,%(c)s,)"
async with conn.cursor() as cur:
    args = []
    for d in data:
        args.append(await cur.mogrify(ROW_SQL, d))
    await cur.execute(b'INSERT INTO entries (a, b, c) VALUES ' + b','.join(args))
```
