### ISSUE TITLE
session object integration

### ISSUE THREAD

**Issue by paultag** [aio-libs/aiopg#19]
Hey aiopg people! Nice work so far, loving this!

It'd be awesome to find a way to get `session` objects working with asyncio!

**Comment by iamale** [comment]
Actually, you _can_ make `async def __getattr__`, it would just require `await` which probably looks a bit weird:

```
>>> class User:
...     async def __getattr__(self, name):
...         # do something async
...         return name
...
>>> User().photos
<coroutine object __getattr__>
>>> async def main():
...     user = User()
...     print(await user.friends)
...
>>> asyncio.get_event_loop().run_until_complete(main())
"friends"
```

**Comment by iamale** [comment]
This should work with `@property` as well. Generator and async functions are just functions that return generators and coroutines.

Won't work for _all_ magic methods, though — for example, `__repr__` is expected to always return strings.
