### ISSUE TITLE
Handle PostgreSQL server restart with opened connections

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiopg#20]
Currently client 'hangs'.
Probably the best way to process the issue is adding timeouts.

**Comment by chusov** [comment]
Sorry for the stupid question.
How to handle restart the server when use aiopg in aiohttp
Example create app:
```
 app = Application(loop=loop)
 app['db'] = yield from create_engine(dsn)
```
Then on request:
```
with (yield from request.app['db']) as conn:
   res = yield from conn.execute(query)
``` 
If after start app PostgreSQL restart get error until the app is restarted
```
psycopg2.DatabaseError: server closed the connection unexpectedly
```

**Comment by asvetlov** [comment]
I'll fix it shortly.

**Comment by imbusy** [comment]
Was this fixed? I am trying to figure out what is the best way to deal with database restarts and potentially PostgreSQL IP address switches.

**Comment by rgacote** [comment]
One way to address this issue is to catch the database error, force the connection to close, then return it to the pool. I've tested this by both reloading and restarting the Postgres database. Once the DB is back up, the pool re-connects.  Not sure this is fixable in the actual pool code since the pool does not know much about the actual connection once it is initiated. 

```python
  try:
    connection = await.pool.acquire()
    cursor = await connection.cursor()
    await cursor.execute(some sql)
    row = await cursor.fetchone()
  except psycopg2.OperationalError as err:
    # Log error.
    # Possibly check for different types of errors to handle.
    # Close the connection
    try:
        if cursor:
          cursor.close()
          cursor = None
    except:
        pass

    try:
        if connection:
            connection.close()
    except:
        pass

# Normal closing close and give back to pool
if cursor:
  cursor.close()
if connection:
  connection.close()
  await.pool.release(connection)


```

**Comment by asvetlov** [comment]
For now the main stopper for the issue is missing test environment.
From my perspective it should be done by running postgres server in docker container -- we can start/stop it manually easy then.
Also I want to convert tests into py.test styled ones.

**Comment by GMLudo** [comment]
@rgacote: Thanks for this recipe.
The main issue is to catch the exception each time you execute a query, however, in the aiohttp context, a specific middleware should handle that behind the scene.

**Comment by rgacote** [comment]
Good point regarding the middleware.
Still new to aiohttp and learning best practices.

On Tue, Mar 8, 2016 at 4:33 PM, Ludovic Gasc <notifications@github.com>
wrote:

> @rgacote <https://github.com/rgacote>: Thanks for this recipe.
> The main issue is to catch the exception each time you execute a query,
> however, in the aiohttp context, a specific middleware should handle that
> behind the scene.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiopg/issues/20#issuecomment-193977989>.
>



-- 
Raymond Cote, President
voice: +1.603.924.6079 email: rgacote@AppropriateSolutions.com skype:
ray.cote

**Comment by asvetlov** [comment]
It can be done in aiopg itself I believe.
My idea is:
1. Terminate both cursor and connection on server shutdown (receiving `psycopg2.OperationalError` and maybe `psycopg2.InternalError`).
2. On releasing connection to pool check closed state (already done, see https://github.com/aio-libs/aiopg/blob/master/aiopg/pool.py#L229)

Good news: all `aiopg` test suite uses docker containers now, so I can make explicit automated test for server shutdown/restart. 

Stay tuned :)

**Comment by GMLudo** [comment]
@asvetlov: it sounds great :-)

**Comment by Gr1N** [comment]
@asvetlov hi, any progress on issue?

**Comment by asvetlov** [comment]
Nope

**Comment by Gr1N** [comment]
Maybe any plans or estimates?

**Comment by asvetlov** [comment]
It's an open issue.
Maybe you would mind to be a volunteer?
At start we need just a test which shuts down a server with opened connection to it and displays what happens.

**Comment by Gr1N** [comment]
I have no free time for activities like this for now... But I will think about it, maybe I can try to do something.

**Comment by beezz** [comment]
@asvetlov I've created simple test for this case, here: https://github.com/beezz/aiopg/blob/916592817dffb221ab6ca8f533ea5a9b1341fa16/tests/test_closed_connection.py

And here is the result: https://gist.github.com/beezz/3bad805e0c82b4a809b1c5f61ed46fcf

**Comment by asvetlov** [comment]
Perhaps it's fine to get `OperationalError`.
If aiopg was used with `create_pool` the closed connection is dropped from pool and next call will acquire new db connection.

@beezz your test should be incorporated into aiopg test suite.
Would you create a Pull Request?

**Comment by beezz** [comment]
@asvetlov Here you  go #195

**Comment by asvetlov** [comment]
Tested by #195
