### ISSUE TITLE
Random "cursor.execute() called while another coroutine is already waiting for incoming data" under load

### ISSUE THREAD

**Issue by themylogin** [aio-libs/aiopg#216]
I have a trivial `aiohttp.web` application that executes SQL requests via `aiopg` sqlalchemy integration. It's as simple as:

    import aiohttp.web
    from aiopg.sa import create_engine

    app = aiohttp.web.Application()

    async def rows(request):
        async with request.app["db"].acquire() as db:
            return aiohttp.web.json_response(list(await db.execute("SELECT * FROM table")))

    app.router.add_route("GET", "/rows", rows)

    async def init(app):
        app["db"] = await create_engine(host="postgres", user="visio", password="visio", database="visio")

    if __name__ == "__main__":
        loop = asyncio.get_event_loop()
        handler = app.make_handler()

        loop.run_until_complete(init(app))

        loop.run_until_complete(loop.create_server(handler, "0.0.0.0", 80))
        loop.run_forever()

When server load reaches 100 rps, this error starts appearing randomly:

    RuntimeError: cursor.execute() called while another coroutine is already waiting for incoming data
      File "aiohttp/server.py", line 261, in start
        yield from self.handle_request(message, payload)
      File "aiohttp/web.py", line 88, in handle_request
        resp = yield from handler(request)
      File "visio_longer/views/communicate/__init__.py", line 72, in legacy_communicate
        device = await query_device(db, access_token)
      File "visio_longer/views/communicate/__init__.py", line 31, in query_device
        (Device.access_token == access_token)
      File "aiopg/utils.py", line 72, in __await__
        resp = yield from self._coro
      File "aiopg/sa/connection.py", line 103, in _execute
        yield from cursor.execute(str(compiled), post_processed_params[0])
      File "aiopg/cursor.py", line 103, in execute
        waiter = self._conn._create_waiter('cursor.execute')
      File "aiopg/connection.py", line 186, in _create_waiter
        'already waiting for incoming data' % func_name)

It happens with random queries at random times, once in a few days, sometimes these errors come in bunch of 4 or 2. Is there something wrong with my code? `aiohttp` and `aiopg` versions are latest from pip

**Comment by themylogin** [comment]
I've also faced https://github.com/aio-libs/aiopg/issues/144 where CancelledError's were coming from `aioes` and `aioredis`, not from `aiopg`, maybe this is the same problem? E.g. one HTTP connection handler is cancelled, aiopg connection is being returned to pool (while still executing some query), being acquired by another HTTP connection, which tries to execute another query on it while first is not finished.

**Comment by jettify** [comment]
We can add check self._conn.isexecuting() in pool https://github.com/aio-libs/aiopg/blob/d4cef365f79944056ced461e81bfb483787ac784/aiopg/pool.py#L188-L189  and drop connection if connection is dirty, but real question what is going on with cancellation logic, may be `_conn.cancel()` sometimes leaves connection in dirty state?

**Comment by themylogin** [comment]
@jettify yes, you are right, when connection is being cancelled, there are a few event loop ticks when it is in inconsistent state:

    @asyncio.coroutine
    def test_cancellation_is_synchronous(connect, loop):
        from psycopg2.extensions import TRANSACTION_STATUS_IDLE

        fut = asyncio.Future(loop=loop)

        @asyncio.coroutine
        def inner():
            fut.set_result(None)
            yield from cur.execute("SELECT pg_sleep(10)")

        conn = yield from connect()
        cur = yield from conn.cursor()
        task = ensure_future(inner(), loop=loop)
        yield from fut
        yield from asyncio.sleep(0.1, loop=loop)

        task.cancel()

        had_inconsistent_state = False
        for tick in range(10):
            yield from asyncio.sleep(0, loop=loop)
            transaction_status = conn._conn.get_transaction_status()
            state = {
                "transaction_status": transaction_status,
                "waiter": conn._waiter,
                "tick": tick,
            }
            print("%(tick)d: transaction_status=%(transaction_status)r, waiter=%(waiter)r" % state)
            if not (transaction_status != TRANSACTION_STATUS_IDLE or conn._waiter is None):
                had_inconsistent_state = True

        assert not had_inconsistent_state

The output is following:

    0: transaction_status=1, waiter=<Future cancelled>
    1: transaction_status=1, waiter=<Future pending cb=[_release_waiter(<Future pendi...sk._wakeup()]>)() at /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py:344]>
    2: transaction_status=1, waiter=<Future pending cb=[_release_waiter(<Future pendi...sk._wakeup()]>)() at /usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py:344]>
    3: transaction_status=0, waiter=<Future finished exception=QueryCanceledError('canceling statement due to user request\n',)>
    4: transaction_status=0, waiter=<Future finished exception=QueryCanceledError('canceling statement due to user request\n',)>
    5: transaction_status=0, waiter=<Future finished exception=QueryCanceledError('canceling statement due to user request\n',)>
    6: transaction_status=0, waiter=<Future finished exception=QueryCanceledError('canceling statement due to user request\n',)>
    7: transaction_status=0, waiter=None
    8: transaction_status=0, waiter=None
    9: transaction_status=0, waiter=None

States from 3 to 6 are invalid: `transaction_status` is `TRANSACTION_STATUS_IDLE` (so connection is successfully returned to the pool), but `waiter` is not `None`, so attempt to use a connection causes `RuntimeError`

**Comment by deansg** [comment]
This still happens to me with aiopg 1.4.0. Was this supposed to be fixed already? Is there anything I can do in my code to overcome this?

**Comment by ulidtko** [comment]
Occurred on aiopg==1.3.3 for me too.

Although in my case, it's completely my fault: in an app, I've reused the same DB connection (note: not pool, but *already acquired connection*) — to run queries in 2 independent relatively long-running async tasks.  So naturally, under load the tasks race each other to run queries on the connection — crashing occasionally with
> RuntimeError: cursor.execute() called while another coroutine is already waiting for incoming data

Which seems completely correct, and indicates an issue in my app — not in `aiopg` library.

@deansg make sure you don't do something similar. Don't reuse a single connection across concurrent coroutines/tasks performing numerous queries. Each one should better use its own connection. HTH
