### ISSUE TITLE
when a new release?

### ISSUE THREAD

**Issue by vir-mir** [aio-libs/aiopg#225]
https://github.com/aio-libs/aiopg/blob/master/CHANGES.txt

0.13.0 (2016-11-XX) already 2016-12-xx

**Comment by jettify** [comment]
@asvetlov if you do not mind I can make release today at night or on weekends. We have couple interesting pending PRs https://github.com/aio-libs/aiopg/pull/223 and https://github.com/aio-libs/aiopg/pull/219 but lets release them in next version.

**Comment by asvetlov** [comment]
@jettify OK.

**Comment by asvetlov** [comment]
0.13 is released
