### ISSUE TITLE
How to create a connection pool on app start and use it?

### ISSUE THREAD

**Issue by leemalmac** [aio-libs/aiopg#270]
Hi!

I'm building a web app. I wan't to create a connection pool when the server starts and use connections from this pool. I've seen examples and the source code, but I'm not able to complete this task. I'm not Python newbie and used NodeJS, but I'm currently trying Python's asyncio (with async/await).

In the example we use `async with aiopg.create_pool(...) as pool`, if I got it correctly the pool will be closed on `__aexit__`. How to overcome this?

**Comment by popravich** [comment]
Hi,
You can simply not put it in `async with` block:
```python
# option 1a
async def main():
    pool = await aiopg.create_pool(...)
    await my_app.run(pool)
    # after my_app is stopped (eg by KeyboardInterrupt) pool will be ungracefully dropped
    # (connections won't be closed in a proper way)
    # so the better way is:

# option 1b
async def main():
    pool = await aiopg.create_pool(...)
    try:
        await my_app.run(pool)
    finally:
        pool.close()
        await pool.wait_closed()
    # which is basically the same as opt.2:

# option 2
async def main():
    async with aiopg.create_pool(...) as pool:
        await my_app.run(pool)
```

**Comment by leemalmac** [comment]
Thanks, it works.
Do I need to close/free connections manually on operation end?

**Comment by popravich** [comment]
You need to call `pool.close / wait_closed` when your application is done to gracefully shutdown
connections. Otherwise you will be getting many warnings about running coroutines after loop is stopped...

**Comment by jettify** [comment]
I think we can close issue, feel free to reopen in you have more questions.
