### ISSUE TITLE
Asyncio gather assertion error: Don't support server side cursors yet

### ISSUE THREAD

**Issue by VitaliProkurat** [aio-libs/aiopg#277]
Hello, i try run several functions in asyncio.gather

i create connection pool:
```python       
from aiopg.sa import create_engine
engine = await create_engine(...)
```
each function acquire connection from pool before run query
```python
async with engine.acquire() as conn:
    res_proxy = await conn.execute(sql)
    res_proxy.fetchone()
    
```
It seems functions in gather takes the same connection and when results for one function is ready another function also running query via this connection.

Please let me know how to solve problem?
Thanks.

**Comment by glarrain** [comment]
@VitaliProkurat see #60
