### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by Daenyth** [aio-libs/aiopg#314]
It would help in using this library in a codebase with mypy, and since this is a python3-only project, you can use the inline syntax rather than type comments.

**Comment by jettify** [comment]
Sure, eventually I think most projects will add, mypy annotations. Would you like to contribute stub files?

**Comment by Daenyth** [comment]
I can probably do some here and there, though a full codebase-wide tagging effort would be difficult. I'll see what I can do

**Comment by Pliner** [comment]
Resolved by #813 and available as [1.3.0b2](https://pypi.org/project/aiopg/1.3.0b2/)
