### ISSUE TITLE
How to non-asynchronously open a pool which I can use asynchronously later?

### ISSUE THREAD

**Issue by Daenyth** [aio-libs/aiopg#337]
My use case is for a kinesis consumer application. Due to the KCL class interface, I can't make my methods async, so instead, I give my consumer an event loop object and have it run my async db operations on that event loop. The problem is that I can't figure out how to also pass it a connection pool, synchronously, because I'd prefer not to open a new db connection for each kinesis record on the stream. Because `create_pool` is intended to be used as `async with`, I don't see how I can pass the created pool to non-async functions

**Comment by jettify** [comment]
Hi
you can do something like  in you sync code `pool = loop.run_until_complete(create_pool())`, point of `async with` to do execute finalizer:
```
poo.close()
loop.run_until_complete(pool.wait_closed())
```
you can do it manually.
