### ISSUE TITLE
psycopg2.OperationalError after an idle period

### ISSUE THREAD

**Issue by barrachri** [aio-libs/aiopg#338]
From time to time I get this error:
```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
Mostly when I call some views that do operations with the db after an idle period (like leaving the browser open and doing a sign-up after 5 minutes).

The app and the db are running inside a docker service.

This is the code:

```python
try:
    async with engine.acquire() as conn:
        query = models.User.select().where(models.User.c.email == email)
        result = await conn.execute(query)
        user = await result.fetchone()
        # update last_access if user is not None
        if user is not None:
            query = models.User.update().where(models.User.c.id == user.id).values(last_access=func.now())
            await conn.execute(query)
except OperationalError as err:
    logger.error(f"error while db connection: {err}")
    raise web.HTTPInternalServerError()
```

**Comment by asvetlov** [comment]
This *may* happen, especially if your code is executed on one node and Postgres server is hosted on other.
The best you can do is failing with a guess to try again.
The error text is come from `psycopg2` internals, it means aiopg itself is not related to the problem most likely and connection from aiopg client to server is really broken somehow.

**Comment by barrachri** [comment]
Thanks @asvetlov.
I'll try to implement the `if failed try again` logic.
