### ISSUE TITLE
SQLAlchemy Dialects

### ISSUE THREAD

**Issue by jairhenrique** [aio-libs/aiopg#345]
It would be nice if SQLAlchemy support was done using the [dialects](http://docs.sqlalchemy.org/en/latest/dialects/index.html).

```python
from sqlalchemy import create_engine
engine = create_engine('postgresql+aiopg://...')
....
```

**Comment by asvetlov** [comment]
Sorry, it's impossible by reasons described here: aio-libs/aiomysql#189
