### ISSUE TITLE
Should cursor.mogrify be coroutine?

### ISSUE THREAD

**Issue by drtyrsa** [aio-libs/aiopg#352]
Hi. `Cursor.mogrify` is [documented](https://aiopg.readthedocs.io/en/stable/core.html#aiopg.Cursor.mogrify) as a regular method, not coroutine. But in source code it's decorated with `asyncio.coroutine`, while doen't have any `yield from` instructions.

So we can:

1. Remove `asyncio.coroutine` decorator. Regular method seems to be more correct here, but it would be a breaking change.
2. Fix the docs.

What do you think?

**Comment by Pliner** [comment]
It was fixed a while ago.
