### ISSUE TITLE
Is there a good way to create aiopg pytest.fixture?

### ISSUE THREAD

**Issue by royxue** [aio-libs/aiopg#358]
As for test, what's the best way to create aiopg engine/connections/transaction for the sqlalchemy async model functions?

I tried several ways but didnt find a good solution.

**Comment by jettify** [comment]
See example here, https://github.com/aio-libs/aiohttp_admin/blob/c90f1d4f4cff28509a0b3334520ba812ee00aeac/tests/db_fixtures.py#L58-L77 you may want to tweak example a bit, use yield fixture instead of addfinalizer

**Comment by Daenyth** [comment]
I have some stuff set up
