### ISSUE TITLE
Add support for async session.query(MyModel) operations

### ISSUE THREAD

**Issue by thedrow** [aio-libs/aiopg#367]
I'd like to be able to query the database using SQLAlchemy's Query API e.g.
```python
session_factory = sessionmaker(bind=some_engine)
session = scoped_session()()
async session.query(MyModel).one()
```
Right now it seems that it is only possible to run raw SQL queries asynchronously.
I'm not sure that sessions can be created using what we currently have. If not, we need to implement them as well somehow.
Is it possible to add async/await support to the Query API?

**Comment by asvetlov** [comment]
I'd like it too but it is impossible unfortunately.
SQLAlchemy internals allow to work synchronously only on ORM level.
