### ISSUE TITLE
Aiopg blocks event loop during query cancel

### ISSUE THREAD

**Issue by kelvich** [aio-libs/aiopg#375]
If cursor is configured with timeout, then upon expiration of this timeout psycopg2 tries to call libpq's PQcancel() which tries to connect to postgres via different connection and close previous backend. In case when server is really unaccessible this will block event loop. Also this connection attempt doesn't inherit timeout of aiopg.connect().

Here is script to reproduce problem: https://gist.github.com/kelvich/7ca3dcaa279f76e004b88e40c7354025

It starts two loops in separate coroutines, one of which is doing database queries, other one just prints "tick" every second to illustrate blocking. To block evloop one need to block network connections to database, for example in docker container:

```sh
# in first console
docker run -p 5432:5432 --name pg postgres:alpine
# in second console
python3 ./aiopg_stuck.py
```

then we can go inside our container with postgres `docker exec -ti -u root --privileged pg sh` and block network:

```sh
apk --update add iptables
iptables -A INPUT -j DROP && iptables -A OUTPUT -j DROP
```

evloop will hang after that.

**Comment by jettify** [comment]
This is very interesting finding, let me clarify something, timeout occurs here?

https://github.com/aio-libs/aiopg/blob/7d8f58b83b2482de0ef1bfced2d0576e9f8be347/aiopg/connection.py#L230-L231
And we closing connection here?
https://github.com/aio-libs/aiopg/blob/7d8f58b83b2482de0ef1bfced2d0576e9f8be347/aiopg/connection.py#L234-L235
?
