### ISSUE TITLE
Create a django database backend

### ISSUE THREAD

**Issue by thedrow** [aio-libs/aiopg#38]
Currently there's no database backend using aiopg for Django.
Two backends should be implemented one that provides the same behavior as the original psycopg2 adapter and one that also provides connection pooling. The first backend should be a drop-in replacement.
How do we advance this issue further?
I assume that yield from should be added [here](https://github.com/django/django/blob/master/django/db/backends/postgresql_psycopg2/base.py#L137) and [here](https://github.com/django/django/blob/master/django/db/backends/postgresql_psycopg2/base.py#L163) but there are probably other places where we should be async.
Care to provide some feedback? I'll create a pull request once I will have further instructions on how to proceed.

**Comment by dkgitdev** [comment]
I'd like to reopen it as I'm here with the actual use case for AIO in Django: Celery.

Our backend processing some background imports using it. It does the following stuff:

- get image urls;
- get all images and save them to db in an async way.

So I have something like `loop.run_until_complete(asyncio.gather(*[asyncio.ensure_future(fetch_and_save(*args, **kwargs))]))` and it'll be nice to use current implementation of your async library as a django backend, so I can control various stuff such as max pool size (for example, psycopg2 which we currently use, spawns lots of connections with no way to limit them using django configuration)
