### ISSUE TITLE
set timeout on SAConnection

### ISSUE THREAD

**Issue by DeoLeung** [aio-libs/aiopg#380]
Hi,

Can I set timeout on SAConnetion separately? 
currently I can only set it when I create the engine.

**Comment by jettify** [comment]
I do not think so. What is your use case? Connections created by pool also managed by pool, you can create new raw connection outside pool and set required timeouts there.

**Comment by jettify** [comment]
closing for now, feel free to open new issue

**Comment by DeoLeung** [comment]
my case was that generally my service want a short timeout to avoid sql running too long, but there would be some exception that we know the sql will be a long run.

and you are right, maybe I would just create another raw connection to do it
