### ISSUE TITLE
Any way to stream results asynchronously?

### ISSUE THREAD

**Issue by Daenyth** [aio-libs/aiopg#385]
Since psycopg2 doesn't support named cursors in async mode, is there any way to stream results?

Is it possible to use aipog's interface synchronously to stream results? If so, how? Do I need to use raw psycopg2 directly?

**Comment by asvetlov** [comment]
No way, sorry.
IIRC [asyncpg](https://magicstack.github.io/asyncpg/current/) supports the feature.

**Comment by jettify** [comment]
closing feel free to create new issue if you have more questions

**Comment by WGH-** [comment]
Note that there's nothing preventing you from creating named cursors yourself:
```python
async with cur.begin():
    await cur.execute(f"DECLARE tmp1 CURSOR FOR {q}")
    while True:
        await cur.execute("FETCH 100 tmp1")
        batch = await cur.fetchall()
        if not batch:
            break
        for row in batch:
            print(row)
```
