### ISSUE TITLE
Error with sqlalchemy

### ISSUE THREAD

**Issue by rightaway** [aio-libs/aiopg#43]
I'm getting an error when using sqlalchemy and nothing is getting inserted.

```
Fatal error on aiopg connection: bad state in _ready callback
connection: <aiopg.connection.Connection object at 0x7f0c3ab44710>
```

Not sure what's causing it, maybe this additional information will help. Is it possible to use a sqlalchemy model defined using declarative to get the table object used by aiopg?

```
from aiopg.sa import create_engine
engine = create_engine(database='db')
Base.metadata.bind = engine
table = Base.metadata.tables['table']
```

And is it possible to only provide the 'database' argument like above if in the non-aiopg version I'm defining it as follows, with just a db name because it's using local authentication.

```
engine = engine_from_config({'sqlalchemy.url': 'postgresql+psycopg2:///db'})
```

I'm running the insert statements like this (not sure if I need the commented parts).

```
    with (yield from engine) as conn:
        # tr = yield from conn.begin()
        yield from conn.execute(table.insert(), *multivalues)
        # yield from tr.commit()
```

**Comment by asvetlov** [comment]
No, you cannot use *aiopg* with *SQLAlchemy's* **ORM** layer.
