### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by smagafurov** [aio-libs/aiopg#436]
SyntaxError in python 3.7 (name `async` is not allowed)

```
  File "/home/travis/build/05bit/peewee-async/peewee_async.py", line 29, in <module>
    import aiopg
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/aiopg/__init__.py", line 5, in <module>
    from .connection import connect, Connection, TIMEOUT as DEFAULT_TIMEOUT
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/aiopg/connection.py", line 109
    self._conn = psycopg2.connect(dsn, async=True, **kwargs)
                                           ^
SyntaxError: invalid syntax
```

**Comment by asvetlov** [comment]
Should be easy to fix: just add `kwargs['async'] = True`.

Would you create a Pull Request?

**Comment by smagafurov** [comment]
https://github.com/aio-libs/aiopg/pull/437

**Comment by Pajinek** [comment]
Any progress?

**Comment by Gr1N** [comment]
+1

**Comment by BrokeRU** [comment]
`psycopg2` guys have already fixed this issue. Now the argument should be `async_`, not `async`. See: https://github.com/psycopg/psycopg2/issues/714#issuecomment-390154680

**Comment by JustinTArthur** [comment]
@BrokeRU this has been addressed in PR #437 already. Just awaiting approval.

**Comment by vir-mir** [comment]
in master. @asvetlov release new version please

**Comment by asvetlov** [comment]
Nice!
Thank you @vir-mir

**Comment by asvetlov** [comment]
Done
