### ISSUE TITLE
psycopg2 renaming

### ISSUE THREAD

**Issue by flip111** [aio-libs/aiopg#445]
I think this library triggers the following warning:

```
env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```

i noticed this while running `adev runserver` from aiohttp-devtools

**Comment by playpauseandstop** [comment]
+1 here

`aiopg` installs `psycopg2` even `psycopg2-binary` listed in `requirements.txt` file,

```
...
Collecting psycopg2-binary==2.7.4 (from -r requirements.txt (line 27))
  Downloading psycopg2_binary-2.7.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 316kB/s
...
Collecting psycopg2>=2.5.2 (from aiopg==0.13.2->-r requirements.txt (line 5))
  Downloading psycopg2-2.7.4-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 378kB/s 
...
```

But I am not sure what how to handle this `psycopg2` rename, looks like for now only way is to ignore that warning.

**Comment by pdautry** [comment]
In fact `psycopg2` is listed as a dependency in SQLAlchemy so unless SQLAlchemy updates this [line](https://github.com/zzzeek/sqlalchemy/blob/master/setup.py#L159), `pip` will continue to install `psycopg2` even if `psycopg2-binary` is in `requirements.txt`.

The package manager in Python is a real pain... It cannot notice that even if the package name differs they implement the same module. If it could adding `psycopg2-binary` before installing sqlalchemy would have solved this issue...

**Comment by johndoe46** [comment]
+1 here.

I don't think there's a `pip3 remove` but `pip3 uninstall psycopg2` worked for me.

**Comment by webknjaz** [comment]
> so unless SQLAlchemy updates this line

@pdautry that's not true. This package does not depend on `sqlalchemy[postgresql]` (with extra), so it doesn't trigger it at all.


AFAICS it's safe to just replace a dependency in here.

**Comment by pdautry** [comment]
> This package does not depend on sqlalchemy

@webknjaz, I don't really know what you mean here (which package ?) but I read this:
https://github.com/aio-libs/aiopg/blob/master/requirements.txt#L14
and that:
https://github.com/zzzeek/sqlalchemy/blob/master/setup.py#L159
so I assume that installing `aiopg` installs `sqlalchemy` which needs `psycopg2` so it installs it anyway.
But whatever, we found a workaround.

> AFAICS it's safe to just replace a dependency in here.

I did not say it's _unsafe_, I said it's _useless_ as explained by the dependency relation highlighted above.

>I don't think there's a pip3 remove

True, thanks ;)

**Comment by SupermanIsEvious** [comment]
@pdautry actually, your assessment is incorrect. 

`SQLAlchemy` does not require `psycopg2`, and in fact supplies extras for the binary as well. 

Additionally, `aiopg` does not require `SQLAlchemy`, that's an extra that will only be automatically installed if you declare it, i.e., `pip install aiopg[sa]`. 

The issue here is that `aiopg` forces an installation of `psycopg2` rather than allowing `psycopg2-binary`. Unfortunately, the questionable decision to split the `psycopg2` distributions makes this a harder problem to solve. 

Either `aiopg` needs to update https://github.com/aio-libs/aiopg/blob/master/setup.py#L7 to install from the binary package, or they should provide a separate package in the same manner of `psycopg2` so that users can select between the two.

**Comment by pdautry** [comment]
@SupermanIsEvious, ok, I have not been watching this issue for a long time, but I just tried to understand why I encountered the error that I tried to solve with a workaround explained here : https://github.com/aio-libs/aiopg/issues/445#issuecomment-388626796
I fully agree with these statements : 

> The issue here is that aiopg forces an installation of psycopg2 rather than allowing psycopg2-binary. Unfortunately, the questionable decision to split the psycopg2 distributions makes this a harder problem to solve.

> Either aiopg needs to update https://github.com/aio-libs/aiopg/blob/master/setup.py#L7 to install from the binary package, or they should provide a separate package in the same manner of psycopg2 so that users can select between the two.

**Comment by yabirgb** [comment]
Is there a solution for this?

**Comment by orf** [comment]
I have a PR with a fix, but it does require bumping the minimum sqlalchemy version to `1.2.11`.

We *could* just leave it as it is, pip will throw a small warning about `[postgresql_psycopg2binary]` not being available but will otherwise install just fine.

**Comment by vir-mir** [comment]
@asvetlov  I propose to release the new version. on the approach of the big pull request,  where python <3.5 support will be removed
