### ISSUE TITLE
Is there a way to wrap all transactions in test to rollback them at the end of a test?

### ISSUE THREAD

**Issue by GregEremeev** [aio-libs/aiopg#471]
I use aiopg.sa.create_engine and I'm looking for a way to wrap all transactions in my tests to rollback them at the end of each test to remove all data.
Is it possible?

**Comment by asvetlov** [comment]
The simple answer is "no".
The request is out of the scope of the library.
As far as I know no one database driver has such functionality.

**Comment by GregEremeev** [comment]
@asvetlov Can you suggest any reasonable alternatives?

**Comment by asvetlov** [comment]
[TRUNCATE](https://www.postgresql.org/docs/9.1/static/sql-truncate.html) can help for example.
The problem is not aiopg specific, any solution from the synchronous world should work here.
