### ISSUE TITLE
cannot insert in PostgreSQL 8.1

### ISSUE THREAD

**Issue by Marruixu** [aio-libs/aiopg#473]
Hi,

Recap:
I'm using postgreSQL version 8.1.23 and I got this error:
```
psycopg2.ProgrammingError: syntax error at or near «RETURNING»
LINE 1: INSERT INTO tbl (val) VALUES (E'abc') RETURNING tbl.id
```

This is the code that runs the insert from the demo code in README:

```
    metadata = sa.MetaData()

    tbl = sa.Table('tbl', metadata,
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('val', sa.String(255)))

    await conn.execute(tbl.insert().values(val='abc'))

    async for row in conn.execute(tbl.select()):
        print(row.id, row.val)
```

I've created the engine with **enable_hstore** set to False in order to work with this Postgres version. I am already acquiring connections from this engine and querying _selects_ and they're all working fine.

I've also created tables with **implicit_returning=False**, which I found in source code to prevent adding RETURNING clause, cause I've seen that is not a valid clause in this PostgreSQL version.

But now, I've seen that if no default is defined in column or is None, appears after awaiting query:
`AttributeError: 'NoneType' object has no attribute 'is_callable'`

I don't see clearly how can I set specific dialect or to insert items... :(

Thank you in advance!

**Comment by asvetlov** [comment]
`aiopg.sa` doesn't check postgres server version and doesn't adopt a dialect to it.
PostgreSQL 8.1 is 13 years old and not supported anymore by Postgres team.
The library does not support it as well.

P.S. `RETURNING` appeared in Postgres 9
