### ISSUE TITLE
Many cursor method examples are not correct?

### ISSUE THREAD

**Issue by bitdancer** [aio-libs/aiopg#48]
I realize (now) that the docs say all the methods are coroutines (except close).  However, the examples for fetchone, fetchmany, fetchiter, etc do not use 'yield from' in the examples and I wasted a bit of time wondering why I was getting an empty list from my select statement before I noticed the (correct) example at the top of the section.  Also, the example of using the cursor as an iterator does not work for me (prints no data).  I'm using 0.6.1.

**Comment by jettify** [comment]
Cursor as iterator is known issue see #42. I made PR for removing this feature.

**Comment by asvetlov** [comment]
Thanks for report, David!

I've added `yield from` to documentation examples where it was missing. 
Will publish new release soon.

**Comment by mpaolini** [comment]
We can close this one,  docs and examples are correct  now
