### ISSUE TITLE
Deprecated async lock with Python 3.7

### ISSUE THREAD

**Issue by Pajinek** [aio-libs/aiopg#508]
I received warning with Python 3.7:

```
/usr/local/lib/python3.7/site-packages/aiopg/pool.py:46: DeprecationWarning: 'with (yield from lock)' is deprecated use 'async with lock' insteadwith (yield from pool._cond):
```

**Comment by asvetlov** [comment]
This is a tight fork. We have two options:
1. Drop Python 3.4
2. Live with the deprecation warning.

**Comment by Pajinek** [comment]
1) +1

**Comment by gjcarneiro** [comment]
+1 to drop  Python 3.4.  

The latest two Ubuntu LTS releases, and Debian, have newer Python:
- 16.04 has 3.5.2;
- 18.04 has 3.6.6;
- Latest Debian stable (stretch) has 3.5.3.

**Comment by Carbaz** [comment]
> This is a tight fork. We have two options:
> 
> 1. Drop Python 3.4
> 2. Live with the deprecation warning.

Sooner or later you will have to choose between:

1. Drop Python 3.4
2. Drop Python 3.8++

My thumbs up for 1.

**Comment by asvetlov** [comment]
Any volunteer to replace `@asyncio.coroutine` / `yield from` with `async def` / `await`?

**Comment by gjcarneiro** [comment]
I made a PR #517
