### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by roadscape** [aio-libs/aiopg#528]
Issue https://github.com/aio-libs/aiopg/issues/364 was resolved with PR https://github.com/aio-libs/aiopg/pull/452 back in October, but there hasn't been a 0.16.0 release. (0.15.0 was released Aug 14, 2018)

I attempted to work around this using `dependency_links`, but this doesn't work since `0.15.0` is what's hardcoded on master and [this bug](https://github.com/pypa/setuptools/issues/987) prevents using a newer commit hash.

Could we have a new release soon? :)

**Comment by roadscape** [comment]
Update: after testing `master` I saw lots of `InterfaceError: cursor already closed` errors. So perhaps not quite ready for release. Will dig deeper...

**Comment by vir-mir** [comment]
Yes, this is due to the fact that in `psycopg2` the cursor is not asynchronous.

**Comment by vir-mir** [comment]
New release https://github.com/aio-libs/aiopg/releases/tag/v0.16.0
