### ISSUE TITLE
Fix python support 3.8.0

### ISSUE THREAD

**Issue by vir-mir** [aio-libs/aiopg#533]
The problem with passing tests.
python version 3.8.0a0 https://travis-ci.com/aio-libs/aiohttp/jobs/173498419

**Comment by gjcarneiro** [comment]
From the traceback it seems like a pyflakes bug?  In any case, Python 3.8 is still a long time away.  It seems premature to be testing it already.  At least wait for beta.

**Comment by vir-mir** [comment]
> Из трассировки это похоже на ошибку Pyflakes? В любом случае, до Python 3.8 еще далеко. Кажется преждевременным уже тестировать его. По крайней мере, подождите бета-версию.

Yes, but travis-ci, python 3.8.dev was given over the link `nightly`
In PR, I made the section `nightly` optional https://github.com/aio-libs/aiopg/pull/534/files#diff-354f30a63fb0907d4ad57269548329e3R42

**Comment by Pliner** [comment]
It looks like this issues it outdated(python 3.8 support is added to the CI #754)
