### ISSUE TITLE
idea as fixed bulk update/insert and mogrify

### ISSUE THREAD

**Issue by vir-mir** [aio-libs/aiopg#550]
Hey all. 

We can implement a bulk insert, but we need to decide what to do with **mogrify**.

Im test `psycopg2.extras.execute_batch` in asynchronous style and the result impressed me. 
we replace "executemany" with "mogrify and execute"

Recently, the argument was `use_batch_mode` added to sqlalchemy. https://github.com/psycopg/psycopg2/issues/491#issuecomment-276693067 
> `use_batch_mode`: This flag allows `psycopg2.extras.execute_batch` for `cursor.executemany()` calls performed by the Engine. It is currently experimental but may well become True by default as it is critical for executemany performance.

psycopg documentation: http://initd.org/psycopg/docs/extras.html#psycopg2.extras.execute_batch
psycopg implementation: https://github.com/psycopg/psycopg2/blob/master/lib/extras.py#L1185
significant speedup: https://github.com/psycopg/psycopg2/issues/491#issuecomment-276551038

This allows us to make mass requests using `use_batch_mode=True` in `Engine` and will resolve of issues: https://github.com/aio-libs/aiopg/issues/112, https://github.com/aio-libs/aiopg/issues/546.

however, `cursor.mogrify` is an asynchronous function. 
although is doesn't need https://github.com/aio-libs/aiopg/issues/186, https://github.com/aio-libs/aiopg/issues/352 

I propose to change this behavior in version **1.0.0** without backward compatibility.

**Comment by vir-mir** [comment]
I propose to discuss @jettify  @asvetlov @thehesiod @webknjaz

**Comment by webknjaz** [comment]
I think `mogrify` is like this just for interface consistency. Following your logic none of the other coroutine methods in that class need async. But using `async def` means that there will also be a control flow yield to the event loop while with sync methods it wouldn't happen.

**Comment by thehesiod** [comment]
leave this up to jettify/asvetlov :]

**Comment by vir-mir** [comment]
I am ready to wait a week more.  but after I collect the new release candidate, removing async before this function

**Comment by vir-mir** [comment]
preparing release

**Comment by vir-mir** [comment]
started implementing https://github.com/aio-libs/aiopg/pull/632
