### ISSUE TITLE
option to close unused connections in alchemy wrapper

### ISSUE THREAD

**Issue by and800** [aio-libs/aiopg#564]
There are some cases when connection pools are not useful at all (my case - I run my code on a lot of machines simultaneously trying to connect to a single DB, so I want to hold open as few connections as possible).

There should be a simple way to close unused connections. For the raw `Pool` there is the `clear()` method, but for the alchemy engine there is no way to do this. It should be quite easy to resolve this - just expose underlying pool `clear()` method to `Engine`'s public API. Also maybe we can add something like "do not use a pool at all" flag to `Engine` factory, or pass a pool factory to engine (In Sqlalchemy there is a `NullPool` concept for this)

**Comment by asvetlov** [comment]
You have two options at least:
1. use `await create_engine(..., maxsize=1)`
2. If even one connection per machine is too much you can recreate the engine before every SQL request
