### ISSUE TITLE
Add advanced example of making sa select

### ISSUE THREAD

**Issue by AlexKovalevych** [aio-libs/aiopg#57]
I was not able to iterate over a select query result, running from the view. Here is the flow:

i run a repository function from the view:

```python
# views.py
users = yield from find_all()
```

`find_all()` is the function in repository module:

```python
# app/models/user.py
@asyncio.coroutine
def find_all():
    yield from run(User.table.select())
```

finally here is how `run` looks:

```python
# app/models/__init__.py
@asyncio.coroutine
def run(query):
    engine = yield from create_engine(user='test',
                                      database='test',
                                      host='127.0.0.1',
                                      password='test')
    with (yield from engine) as conn:
        yield from conn.execute(query)
```

So the problem is that `users` is a `NoneObject`, but if i iterate the result in the same file where the query is executed (`app/models/__init__.py`) then it works fine:

```python
        res = yield from conn.execute(query)
        for row in res:
            print(row)
```

Could you please add more examples of how to get a query result in such case?

**Comment by AlexKovalevych** [comment]
Ok, i got it:

```python
# app/models/__init__.py
...
    with (yield from engine) as conn:
        result = yield from conn.execute(query)
        return result
```

and 

```python
# app/models/user.py
@asyncio.coroutine
def find_all():
    result = yield from run(User.table.select())
    users = result.fetchall()
    return users
```

that worked, issue can be closed, maybe it will be useful for somebody else.

**Comment by asvetlov** [comment]
Sorry, I've missed your point.
But if you would provide yet another example -- you are welcome.
Just make a Pull Request with example code in `./examples` directory.
