### ISSUE TITLE
PostgreSQL notification support

### ISSUE THREAD

**Issue by spinus** [aio-libs/aiopg#58]
Hi,

do you plan to add support for http://initd.org/psycopg/docs/advanced.html#asynchronous-notifications by any chance?

**Comment by asvetlov** [comment]
@spinus I'll take a look.

**Comment by asvetlov** [comment]
Solved in #64

**Comment by spinus** [comment]
@asvetlov great stuff. Cheers!

**Comment by asvetlov** [comment]
I may release new version soon if you need the feature.

**Comment by spinus** [comment]
@asvetlov No rush, release when you are happy with it.
I did some workarounds in the meantime and it's working, but definitely I'll use this in next few weeks.
