### ISSUE TITLE
Server side cursor support

### ISSUE THREAD

**Issue by kashifrazzaqui** [aio-libs/aiopg#60]
I believe aiopg doesn't allow server side cursor support, are there any plans to change this?

**Comment by asvetlov** [comment]
Sorry, it's impossible now because underlying psycopg2 library doesn't support server side cursors in asynchronous mode.
We need another low-level library for that.

**Comment by kashifrazzaqui** [comment]
Ok thanks

**Comment by glarrain** [comment]
(For the record)

From the [official docs](http://initd.org/psycopg/docs/advanced.html#asynchronous-support) (emphasis mine):
> There are several limitations in using asynchronous connections [...].
> With asynchronous connections it is also not possible to use set_client_encoding(), executemany(), large objects, **named cursors**.

[source](https://github.com/psycopg/psycopg2/blob/2_7_1/doc/src/advanced.rst#asynchronous-support)

Note that
> Psycopg wraps the database server side cursor in **named cursors**.
