### ISSUE TITLE
Extract aiopg.sa as library

### ISSUE THREAD

**Issue by eirnym** [aio-libs/aiopg#62]
this package is almost same in `aiopg` and `aiomysql`. So I think we should extract this package as separate library, shouldn't we?

**Comment by asvetlov** [comment]
Maybe it's a good idea but I'm not ready for it right now.
Both libraries are very similar but differs slightly in API details.
We need synchronize these first.

**Comment by jettify** [comment]
Most significant differences are in transaction handling and two phase commit. Agree regarding synchronization, I've created issue https://github.com/aio-libs/aiomysql/issues/20

**Comment by eirnym** [comment]
@jettify Should we move these parts to some different layer like dialect in SQLAlchemy?

**Comment by asvetlov** [comment]
I suggest inviting "Async DB-API" instead fixing the difference.

On Mon, Jun 29, 2015 at 2:59 PM, Arseny Nasokin <notifications@github.com>
wrote:

> @jettify <https://github.com/jettify> Should we move these parts to some
> different layer like dialect in SQLAlchemy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aio-libs/aiopg/issues/62#issuecomment-116628496>.
>



-- 
Thanks,
Andrew Svetlov

**Comment by jettify** [comment]
agree with @asvetlov , from my point of veiw we need one more sql driver implementation, to put things into perspective. I am thinking about mssql...
