### ISSUE TITLE
Deprecation warnings in asyncio with Python 3.8

### ISSUE THREAD

**Issue by dmajda** [aio-libs/aiopg#622]
When using aiopg with Python 3.8 with warnings enabled, deprecation warnings are emitted at various places where a `loop` argument is passed to `asyncio` APIs. To quote from [What’s New In Python 3.8](https://docs.python.org/3/whatsnew/3.8.html):

> In `asyncio`, the explicit passing of a _loop_ argument has been deprecated and will be removed in version 3.10 for the following: `asyncio.sleep()`, `asyncio.gather()`, `asyncio.shield()`, `asyncio.wait_for()`, `asyncio.wait()`, `asyncio.as_completed()`, `asyncio.Task`, `asyncio.Lock`, `asyncio.Event`, `asyncio.Condition`, `asyncio.Semaphore`, `asyncio.BoundedSemaphore`, `asyncio.Queue`, `asyncio.create_subprocess_exec()`, and `asyncio.create_subprocess_shell()`.

It would be good to fix these warnings. I’m not sure whether it would involve just refactoring few `asyncio` API calls, or whether it would require deeper changes in loop handling inside the library.

**Comment by vir-mir** [comment]
@dmajda what version of aiopg are you using?  in version 1.0.0explicit transfer has been replaced with get_running_loop

**Comment by dmajda** [comment]
We use 1.0.0. Here are some specific places where the warnings pop up:

  * [`connection.py` line 90](https://github.com/aio-libs/aiopg/blob/v1.0.0/aiopg/connection.py#L90)
  * [`connection.py` line 207](https://github.com/aio-libs/aiopg/blob/v1.0.0/aiopg/connection.py#L207)
  * [`pool.py` line 57](https://github.com/aio-libs/aiopg/blob/v1.0.0/aiopg/pool.py#L57)

These were caught by a test suite of one of @energomonitor’s internal projects that uses aiopg (we have warnings enabled when running tests). There may be some more places which our test suite didn’t catch.

**Comment by vir-mir** [comment]
Thank. Yes. I think it will be necessary to do this.

**Comment by seedofjoy** [comment]
Done. Review, please

**Comment by Pliner** [comment]
Resolved by  #642
