### ISSUE TITLE
Closing connection object throws exception

### ISSUE THREAD

**Issue by sumerc** [aio-libs/aiopg#65]
Hi,

I am using aiopg with a Pool object that is shared among coroutines. Every once in a while, randomly I see following error:

psycopg2.ProgrammingError: close cannot be used while an asynchronous query is u
nderway

I can reproduce the issue with following:

<pre><code>
pool = yield from aiopg.create_pool(dsn)
with (yield from pool.cursor(timeout=1.0)) as cur:
    yield from cur.execute("SELECT pg_sleep(2)")
</code></pre>

It seems valid to raise TimeoutError rather than ProgrammingError, I believe. What do you think?

Thanks,

**Comment by asvetlov** [comment]
Got it.

**Comment by kashifrazzaqui** [comment]
We are also facing this issue, can you please patch this.

**Comment by asvetlov** [comment]
What do you mean by *sub-query*?
cusor object is intended to execute only one query in the same time.

**Comment by kashifrazzaqui** [comment]
http://www.postgresql.org/docs/8.2/static/functions-subquery.html

**Comment by bitdancer** [comment]
Changing this from a ProgrammingError to a TimeoutError seems to have been done in 8ca948ec, which also makes sure the connection and cursor are closed when it happens.  Can this issue be closed?

**Comment by asvetlov** [comment]
Not yet. I should fix closing cursor with pending query first.
Will do it next week -- just after making new aiohttp release.

**Comment by sumerc** [comment]
Do we have any estimate for the fix? If sub-query is hard to implement, I think we should include the initial problem as soonn as possible. Because currently this blocks one from implementing a retry policy on specific DB errors. e.g: retry query on TimeOut Error 2 times.

**Comment by asvetlov** [comment]
Fixed, d0e5f86 has explicit test for the issue
