### ISSUE TITLE
An exception in BEGIN does not free up a slot in pool

### ISSUE THREAD

**Issue by hhell** [aio-libs/aiopg#665]
This is likely the same problem as https://github.com/aio-libs/aiopg/pull/487

When an exception on `BEGIN` happens, the connection is left in a broken state, taking up a slot in the pool indefinitely.

Reproduction script (that monkeypatches forced `raise` on `BEGIN`): https://gist.github.com/hhell/0b9aa6759065bd0310f29f3d0ae4c63d

The script hangs on 15th `acquire`, but should complete successfully (considering the `except` catch).

**Comment by Pliner** [comment]
Fixed by https://github.com/aio-libs/aiopg/releases/tag/v1.1.0
