### ISSUE TITLE
aiohttp_session not save_session for manualy created new_session

### ISSUE THREAD

**Issue by businka** [aio-libs/aiopg#698]
as part of request processing will be signout.
I closed the previous session. and I want to issue a new guest session. there is no example in the manual of how to do this. I'm doing just aiohttp_session.new_session (request).
with this approach, aiohttp_session>__init__.py>factory does not call save_session (session._changed == False)

**Comment by Pliner** [comment]
It looks like the issue is connected to https://github.com/aio-libs/aiohttp-session

**Comment by businka** [comment]
sorry
