### ISSUE TITLE
The default read committed isolation level is the wrong choice

### ISSUE THREAD

**Issue by dvarrazzo** [aio-libs/aiopg#699]
Hello, 

I have a project where I experienced serialization failures on a statement:

```
select 1 from file where (id, group_id) = (%s, %s) for update
```

resulting in errors like:

```
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
```

now, I happen to know that the statement above would have orderly blocked in case of concurrency, if run in psycopg or in psql: logged some of the operations of the database and sure enough found:

```
postgres_1    | 2020-07-16 10:30:36.377 UTC [11914] LOG:  statement: BEGIN ISOLATION LEVEL REPEATABLE READ
```

Which led me to find:

https://github.com/aio-libs/aiopg/blob/3fb3256319de766384b4867c7cc6710397bd1a8c//aiopg/cursor.py#L10-L16

this is pretty wrong: the driver is choosing an isolation level that causes side effects, and the behaviour of the program becomes very different from the one it would have in psycopg2.

The right default would be to begin a transaction just with `BEGIN`. Note that, unlike what stated here:

https://github.com/aio-libs/aiopg/blob/3fb3256319de766384b4867c7cc6710397bd1a8c/aiopg/transaction.py#L51-L55

`BEGIN` is not "read committed" behaviour: this is "use the server configured behaviour", which is what selected by `default_transaction_isolation` level, and can be changed at server configuration level, session level.

So, what I think is:

1) The `ReadCommittedCompiler` should actually be implemented as:

```python
class ReadCommittedCompiler(IsolationCompiler):
    name = 'Read committed'

    def begin(self):
        return 'BEGIN ISOLATION LEVEL READ COMMITTED'
```

2) you need a class

```python
class DefaultCompiler(IsolationCompiler):
    name = 'Default'

    def begin(self):
        return 'BEGIN'
```

3) that class should be the default.

```python
 class Cursor: 
     def __init__(self, conn, impl, timeout, echo): 
         # ...
         self._transaction = Transaction(self, IsolationLevel.default)
```

you also probably want to fix #497 to allow the isolation level to be chosen, but at least by default you should leave the server default unaltered.

**Comment by dvarrazzo** [comment]
Reference:

https://www.postgresql.org/docs/current/transaction-iso.html#XACT-REPEATABLE-READ:

> Applications using this level must be prepared to retry transactions due to serialization failures.

you haven't warned your users that they have to be prepared to do that.

**Comment by DzigaV** [comment]
> Reference:
> 
> https://www.postgresql.org/docs/current/transaction-iso.html#XACT-REPEATABLE-READ:
> 
> > Applications using this level must be prepared to retry transactions due to serialization failures.
> 
> you haven't warned your users that they have to be prepared to do that.

Your understanding of these issues is really on another level. Will psycopg3 (and cffi) be native async? I am watching development eagerly. I wish we were a large enough business to sponsor your development.

**Comment by dvarrazzo** [comment]
@DzigaV Well, I am very pleased that aiopg has filled an important gap so far and has allowed many projects to use psycopg2 in asyncio environment. This is a perfectly fixable issue :slightly_smiling_face: 

About funding: I am planning to restart with the project - asking for funds is a project in itself, and the middle of a pandemic seems not to the best moment to elicit businesses' generosity...

**Comment by hlobit** [comment]
Just had the issue. As a workaround I had to explicit the isolation level (as described in #497).

```python
async with conn.cursor() as cur:
    async with cur.begin():
        await cur.execute('SET TRANSACTION ISOLATION LEVEL READ COMMITTED')
        ...
```

It is not expectable to get `could not serialize access due to concurrent update` when you do not specify any isolation level. I don't know if it is even possible to use `cursor.begin()` when you want to use the default isolation level of the server.

**Comment by dvarrazzo** [comment]
@hlobit FYI, you can work around the problem by setting the `_transaction` attribute on the cursor. In my project I have the code dealing with database in classes which have this one as base:

```python
class DbBoundary:
    """
    An object to manage the persistence of a class into the database.
    """

    _pool: Optional[aiopg.Pool] = None

    @asynccontextmanager
    async def cursor(self):
        pool = await self._get_pool()
        with (await pool.cursor()) as cur:
            # Set the connection in read committed isolation level
            # to avoid serialization failures on file lock
            # https://github.com/aio-libs/aiopg/issues/699
            # You can unlock the aiopg version from setup.py when this hack
            # is no more needed.
            cur._transaction = aiopg.Transaction(
                cur, aiopg.IsolationLevel.read_committed
            )
            yield cur

    async def _get_pool(self) -> aiopg.Pool:
        if DbBoundary._pool is None:
            DbBoundary._pool = await aiopg.create_pool("")

        return DbBoundary._pool
```

Subclasses can use `async with self.cursor() as cur: ...` to get a cursor working as expected.

**Comment by Pliner** [comment]
Hi @dvarrazzo, 

Thank you for raising this and for so detailed explanations and suggestions 🔥🔥🔥 

I've created #770 to fix the issue, could you please review it?

**Comment by dvarrazzo** [comment]
Hi @Pliner yes, I noticed it, thank you for taking care of it :)

**Comment by dvarrazzo** [comment]
Hi @Pliner yes, I noticed it, thank you for taking care of it :)

**Comment by Pliner** [comment]
@dvarrazzo @hlobit @DzigaV

https://pypi.org/project/aiopg/1.2.0b2/

Will you be able to test this version in your projects to verify that the issue is resolved?

Thanks
