### ISSUE TITLE
Deprecation warning on 'The loop argument' for Python 3.8

### ISSUE THREAD

**Issue by hawkaa** [aio-libs/aiopg#712]
Hi there,

I'm using `aiopg` version 1.0.0 for my Python 3.8 project. However, it keeps spitting out warnings about a deprecated loop function:

```sh
...aiopg/connection.py:90:
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self._notifies = asyncio.Queue(loop=self._loop)
```

Seems like the loop argument is completely removed: https://docs.python.org/3/library/asyncio-queue.html

What do you think?

**Comment by Pliner** [comment]
Resolved by #642
