### ISSUE TITLE
State of the library

### ISSUE THREAD

**Issue by dralley** [aio-libs/aiopg#748]
Hello,

I notice that there have been only 2 commits merged in the past 2 years.  There is nothing wrong with this, especially if nobody is being paid to maintain the library.  However, if this library is not likely to see much future development for whatever reason, it might be good to document this prominently, with the following outcomes in mind:

* Allowing potential users to properly set their expectations, since most of the other projects under this organization are very actively maintained
* Attracting attention of anyone who might be willing to financially sponsor work on the library
* Attracting attention of anyone who might be willing to help maintain this library
* Promoting forks

Thank you @asvetlov for all of your work on this library, and elsewhere!  You have had an incredible impact on the Python ecosystem.

**Comment by asvetlov** [comment]
The project is looking for a new maintainer.
Sorry, I have no time for it.

Does somebody want to drive the project?
I can help, sure -- but cannot perform the daily routine.
aiohttp and family plus CPython consumes all my spare time.

**Comment by rohitchormale** [comment]
Hi, @asvetlov @Pliner I see some commits after your last reply. But this issue is still opened. Are you guys still looking for a new maintainer ?

**Comment by Pliner** [comment]
Hi @rohitchormale, 

Sorry, I forgot to post an update here, @svetlov had agreed to give me a maintainer role, but to be blunt I do maintenance stuff not so regular.

Anyway, feel free to fix the issues and make PRs, I hope I will be able to review promptly.
