### ISSUE TITLE
Connection handling in web application example

### ISSUE THREAD

**Issue by rudyryk** [aio-libs/aiopg#76]
What is the most generic proper way of handling database connection in real web apps? The naive way is just to create connection pool and pick/release a cursor per-query (or per-request?).

But the naive approach has some pitfalls:

1. The connection break because of database server connection down
2. The connection break after locking invalid query/transaction
3. Unknown reason like #67 etc. 

So what is the way to connect/re-connect which suits basic needs and could face naive approach problems?

It would be great to have some ideas and examples on that in docs.

Thank you!

**Comment by GMLudo** [comment]
It's certainly considered as a quick'n'dirty fix, however, it works. For all daemons, we have a special endpoint where we launch a small SQL query. 

We use monit to ping this endpoint. If monit receives an error, it restarts the daemon.
