### ISSUE TITLE
fetchone() return is not a RowProxy but a generator

### ISSUE THREAD

**Issue by Huastone** [aio-libs/aiopg#77]
tbl2 = sa.Table('usert2', metadata,
　　sa.Column('id', INTEGER, primary_key=True),
　　sa.Column('webid', UUID),
　　sa.Column('totyear', SMALLINT),
　　sa.Column('brewdata', SMALLINT))

engine = yield from create_engine(user='postgres',database='t1',host='127.0.0.1',password='pg')
with (yield from engine) as conn:
query = sa.select([tbl2])
res = yield from conn.execute(query)
alarm=res.fetchone()
print('alarm=',alarm)

Output is :
　　 \<generator object fetchone at 0x7f7b27eff5e8\>

It is not right according to sqlalchemy rules. See below section 'Selecting' :
　　http://docs.sqlalchemy.org/en/rel_1_0/core/tutorial.html#executing

**Comment by Huastone** [comment]
These above is some code paragraph not all, FYI.

**Comment by avanov** [comment]
``fetchone()`` is a coroutine (http://aiopg.readthedocs.org/en/latest/sa.html#aiopg.sa.ResultProxy.fetchone). Use have to yield from the result:
```python
alarm = yield from res.fetchone()
```

**Comment by Huastone** [comment]
Yes, that you said is right! Thank you Avanov.
