### ISSUE TITLE
Don't rollback a transaction if the connection is already closed

### ISSUE THREAD

**Issue by brianmaissy** [aio-libs/aiopg#777]
Caused by #570, in which we close the connection in any situation where we would have cancelled the query, since we don't have an async way of cancelling the query.

One possible situation in which we could find ourselves closing the connection is in the case where a query timed out or was cancelled (in an asyncio sense). In that case, we now close the connection, but the calling code may be inside a transaction context manager, which will try to emit a `ROLLBACK` before exiting the block, since an exception was raised.

The net effect is that instead of getting a `TimeoutError` as excepted, the user gets a `psycopg2.InterfaceError: connection already closed` exception, which gets raised during the handling of the `TimeoutError`. In this case, since we were the ones who closed the connection, and we are also the ones trying to run the `ROLLBACK`, it doesn't seem fair to the user not to deal with it properly (as opposed to if a user runs some cleanup query after a `TimeoutError` was thrown, in which case it would be the user's responsibility to check that the connection is still open).

There are many possible ways to solve this, but I think the most elegant might be just not to run the `ROLLBACK` if the connection is closed. This is nice because it isn't just a workaround for a bug, semantically it makes sense. If the connection is closed, the transaction is over, and there's no need to run a `ROLLBACK`.

**Comment by Pliner** [comment]
>There are many possible ways to solve this, but I think the most elegant might be just not to run the ROLLBACK if the connection is closed. This is nice because it isn't just a workaround for a bug, semantically it makes sense. If the connection is closed, the transaction is over, and there's no need to run a ROLLBACK.

I have merely the same thoughts about the fix.
