### ISSUE TITLE
test_binary_protocol_error produces psycopg2.DatabaseError with psycopg2 2.6.1

### ISSUE THREAD

**Issue by bitdancer** [aio-libs/aiopg#80]
Running the tests on master with psycopg2==2.6.1 and postgres 9.4.3 I get a test failure in test_binary_protocol_error.  Instead of the expected OperationalError, I'm getting a DatabaseError.  One fix would be to look for both, the other would be to check the version (assuming that's the issue).

**Comment by asvetlov** [comment]
Aha, I have postgres==9.4.4 and psycopg2==2.6.1 but libpq version is 9.1

In test `OperationalError` replaced by base class `DatabaseError`.

Fixed by 2d795b4

**Comment by asvetlov** [comment]
Thanks for report.
