### ISSUE TITLE
aiopg1.2 incompatible with peewee-async

### ISSUE THREAD

**Issue by inyutin** [aio-libs/aiopg#807]
Removing ```kwargs.pop('loop', None)``` in [Multiple cursors support](https://github.com/aio-libs/aiopg/pull/801/files#) make peewee-async, library that used aiopg, incompatible. Probably, some other libraries affected too.

The thing is: before 1.2 you was allow to pass loop in kwargs.  Before passing those kwargs to psycopg2, the loop parameter was popped. Now, it is not. Loop is passing to psycopg2 and we get error:
```
psycopg2.ProgrammingError: invalid dsn: invalid connection option "loop"
```

**Comment by Pliner** [comment]
https://pypi.org/project/aiopg/1.2.1/
