### ISSUE TITLE
executing a query on a closed SAConnection throws a non-indicative exception

### ISSUE THREAD

**Issue by brianmaissy** [aio-libs/aiopg#809]
If I create and then close an `SAConnection` and then call `.execute()` on it, it will raise the following exception:

`AttributeError: 'NoneType' object has no attribute 'cursor'`

It originates here:
https://github.com/aio-libs/aiopg/blob/50b0822554706db0bf1fac3f376bebb579af3cef/aiopg/sa/connection.py#L85

Is it possible to check if the connection is closed before using it, and throwing a clearer exception?

**Comment by Pliner** [comment]
Hi @brianmaissy,

Surething. Could you submit PR please?

**Comment by Pliner** [comment]
Fixed by #811
