### ISSUE TITLE
Pool.terminate may be broken.

### ISSUE THREAD

**Issue by obmarg** [aio-libs/aiopg#81]
There's not much documentation around the `Pool.terminate` function and it's expected behaviour, so I'm not sure if this is a bug or me mis-using things.

To shutdown my aiopg pool, I am calling `pool.terminate()`, but this is leaving 10 connections to the database open.  From looking at the [pool.terminate code](https://github.com/aio-libs/aiopg/blob/master/aiopg/pool.py#L111-L113) it appears that only _used_ connections get closed, but un-used ones will still remain open.

From looking around it seems I could then `yield from pool.wait_closed()` to wait for the free connections to close.  This doesn't seem too intuitive to me - since the code is terminating connections that are being used, I'd expect the un-used ones to get closed too.  Is this a bug?

**Comment by asvetlov** [comment]
I'm not sure :)
Let me sleep on the issue. I'll return to aiopg active development next week.

**Comment by asvetlov** [comment]
`pool.wait_closed()` usage is documented in `pool.terminate()` chapter.
