### ISSUE TITLE
aiopg incorrectly installs tests along with aiopg in Python

### ISSUE THREAD

**Issue by rutsky** [aio-libs/aiopg#85]
`packages=find_packages(),` in `setup.py` tells setuptools to include all subdirectories that looks like python package to include it in the distribution (since Python 3.3, according to [documentation](https://pythonhosted.org/setuptools/setuptools.html#using-find-packages) directories even don't need to have `__init__.py`). 

This leads to inclusion in the distribution of aiopg `tests` directory, which is incorrect (this directory may in in source distribution, but must not be in binary distributions, e.g. in wheels).

Similar error exists in at least [aiohttp_debugtoolbar](https://github.com/aio-libs/aiohttp_debugtoolbar).

To solve this issue in aiohttp_cors I explicitly listed packages that I want to include in distribution: https://github.com/aio-libs/aiohttp_cors/commit/22b9ff4efd53921cf763b09810d4767ab5d2b7ca

This issue is one of the reasons of initially putting sources inside `src/` subdirectory in aiohttp_cors.

**Comment by popravich** [comment]
Have you tried it yourself?
The `tar.gz` on pypi is ok -- no tests inside.

**Comment by popravich** [comment]
`find_packages(exclude=["tests"])` works fine as well)

**Comment by rutsky** [comment]
> Have you tried it yourself?

I checked this bug on the wheel package from PyPI:
https://pypi.python.org/packages/3.4/a/aiopg/aiopg-0.7.0-py3-none-any.whl#md5=5411a30a843b5dc73869af4c0e1a50b0
It definitely contains `tests` module, but shouldn't.

> The `tar.gz` on pypi is ok -- no tests inside.

`tar.gz` is a source distribution and it *should* contain tests actually, but they are explicitly excluded in `MANIFEST.in`. I suggest to include them in source distribution.

> `find_packages(exclude=["tests"])` works fine as well)

This will work until other directory that looks like python package will not occur in root directory, e.g. I don't know why `examples` and `docs` are not considered as python packages by `find_packages()`.
Maybe with some version of setuptools/pip/Python they will be included in package and this bug will occur again.
Instead of ignoring all directories that may be considered as python package it's better to explicitly state which directories need to be included as packages of distribution (in this case it's only `aiopg` directory).

**Comment by rutsky** [comment]
I can't reproduce this issue in my environment: `aiopg` wheel built in my virtual environment doesn't include `tests` directory, and during quick examination of setuptools sources I didn't find any logic to include subdirectories except cases when directory contains `__init__.py` file.

The fact is that released `aiopg` wheel on PyPI includes `tests` as package (and e.g. `tests` are being installed in my virtual environment during `pip install aiopg` which is incorrect).

This issue needs further investigation.

**Comment by asvetlov** [comment]
I guess the library *has* `tests/__init__.py` but I've dropped it on switching to `py.test` system.
