### ISSUE TITLE
Support async iterator in ResultProxy

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiopg#92]
```
async for row in conn.exectute("SELECT ..."):
    print(row)
```

**Comment by jettify** [comment]
I tried to implement and found that this API is not very good, because there is no way to close created `ResultProxy` object with cursor inside.  We should encourage:
```python
async with conn.execute("SELECT ...") as result:
    async for record in result:
        print(record)
```

**Comment by asvetlov** [comment]
Maybe. I used dirty trick to close result IIRC.

**Comment by jettify** [comment]
resolved by https://github.com/aio-libs/aiopg/pull/94
